# Generated by Django 6.0.3 on 2026-06-11 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_habit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='date',
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion', models.BooleanField(default=False)),
                ('logdate', models.DateField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.habit')),
            ],
        ),
    ]
