# Generated by Django 6.0.3 on 2026-06-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_habitcategory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='max_streak',
            field=models.IntegerField(default=0),
        ),
    ]
